manual_provinces = {
    "Katowice": "województwo śląskie",
    "Bielsko-Biała": "województwo śląskie",
    "Goczałkowice-Zdrój": "województwo śląskie",
    "Tychy": "województwo śląskie",
    "Gliwice": "województwo śląskie",
    "Żywiec": "województwo śląskie",
    "Mikołów": "województwo śląskie",
    "Pszczyna": "województwo śląskie",
    "Częstochowa": "województwo śląskie",
    "Chorzów": "województwo śląskie",
    "Jaworzno": "województwo śląskie",
    "Milówka": "województwo śląskie",
    "Bytom": "województwo śląskie",
    "Myszków": "województwo śląskie",
    "Rajcza": "województwo śląskie",
    "Miasteczko Śląskie": "województwo śląskie",
    "Sosnowiec": "województwo śląskie",
    "Siemianowice Śląskie": "województwo śląskie",
    "Ruda Śląska": "województwo śląskie",
    "Tarnowskie Góry": "województwo śląskie",
    "Czeladź": "województwo śląskie",
    "Mysłowice": "województwo śląskie",
    "Czerwionka-Leszczyny": "województwo śląskie",
    "Dąbrowa Górnicza": "województwo śląskie",
    "Koniecpol": "województwo śląskie",
    "Łodygowice": "województwo śląskie",
    "Siewierz": "województwo śląskie",
    "Wojkowice": "województwo śląskie",
    "Będzin": "województwo śląskie",
    "Kiczyce": "województwo śląskie",
    "Zawiercie": "województwo śląskie",
    "Sławków": "województwo śląskie",
    "Kłobuck": "województwo śląskie",
    "Szczekociny": "województwo śląskie",
    "Włodowice": "województwo śląskie",
    "Skoczów": "województwo śląskie",
    "Bieruń": "województwo śląskie",
    "Nieborowice": "województwo śląskie",
    "Koziegłowy": "województwo wielkopolskie",
    "Korbielów": "województwo śląskie",
    "Łaziska Górne": "województwo śląskie",
    "Harbutowice": "województwo małopolskie",
    "Świętochłowice": "województwo śląskie",
    "Lubliniec": "województwo śląskie",
    "Niegowonice": "województwo śląskie",
    "Wisła Wielka": "województwo śląskie",
    "Czechowice-Dziedzice": "województwo śląskie",
    "Lędziny": "województwo śląskie",
    "Knurów": "województwo śląskie",
    "Kroczyce": "województwo śląskie",
    "Kozy": "województwo śląskie",
    "Radzionków": "województwo śląskie",
    "Strumień": "województwo śląskie",
    "Kolonia": "województwo małopolskie",
    "Mierzyn": "województwo zachodniopomorskie",
    "Korbielów": "województwo śląskie",
    "Łódź": "województwo łódzkie",
    "Węgierska Górka": "województwo śląskie",
    "Piekary Śląskie": "województwo śląskie",
    "Kędzierzyn-Koźle": "województwo opolskie",
    "Suszec": "województwo śląskie",
    "Paczyna": "województwo śląskie",
    "Nakło Śląskie": "województwo śląskie",
    "Leśna": "województwo dolnośląskie",
    "Bujaków": "województwo śląskie",
    "Nieznanice": "województwo śląskie",
    "Koszęcin": "województwo śląskie",
    "Łazy": "województwo śląskie",
    "Mirosław": "województwo wielkopolskie",
    "Bażanowice": "województwo śląskie",
    "Jasienica": "województwo śląskie",
    "Jaworze": "województwo śląskie",
    "Paczyna": "województwo śląskie",
    "Paczyna": "województwo śląskie",


}